### PR TITLE
Removing unnecessary `@Autowired` annotation from generated constructors

### PR DESCRIPTION
**Pull request by airborn**
`@Autowired` is no longer needed on Spring constructors so removing it.

I cannot see any particular reason for `@NoArgConstructor` on `BlogsPageRequestHandler`, so removing this one as well.

### CODE REVIEW

**Comment by airborn** [comment]
Looks like there is more unneeded  `@NoArgConstructor` that actually breaks the code.

**Comment by goostleek** [comment]
> Looks like there is more unneeded @NoArgConstructor that actually breaks the code.

What do you actually mean by _"breaks the code"_?

**Comment by airborn** [comment]
Having both no arg and all arg constructor without @Autowire causes Spring to prefer the no arg one leading to NPEs. No arg ctors can be removed from services but I need to review it more carefully.

**Comment by goostleek** [comment]
But how it is possible our tests passed so far without any errors?

**Comment by airborn** [comment]
Tests do not cover creating those services through Spring. Issue should be only with `BlogsPageRequestHandler` and `MailingPageRequestHandler` which have both all arg and no arg constructors. I'm removing the no arg one as it is not used.

**Comment by tdziurko** [comment]
Unfortunately all beans that are used with Wicket @SpringBean annotation should have no-args constructor due to some serialization issues.
More details here: http://markmail.org/message/xggw6ajuxz22rllh

I will prepare a check that makes sure this constraint is fulfilled.

**Comment by goostleek** [comment]
@tdziurko This is not a mandatory requirement. We already had a [discussion in that matter on SO](https://stackoverflow.com/questions/35260608/wicket-springbean-and-spring-autowired-with-injection-via-constructor/36324808#36324808). The solution for that is to add an [Objenesis](https://mvnrepository.com/artifact/org.objenesis/objenesis) dependency and you can omit no-args constructor.

**Comment by tdziurko** [comment]
I had an issue that Spring beans were not properly injected into backing bean that was injected into the page instance using `@SpringBean` annotation, problem still existed despite having Objenesis in classpath. You can check my starter with this issue here: https://github.com/tdziurko/wicket-spring-bean-issue

**Comment by airborn** [comment]
I'm not able to reproduce such an error in `jvm-bloggers` after visiting every view in the application.

**Comment by tdziurko** [comment]
Ok, so leave it as is. Maybe it won't hit us or it's more project-related that I thought.

**Pull request merged**
