### PR TITLE
Add sorting to blog list in the admin panel, closes #442

### LINKED ISSUE #442: Add sorting to blog list in the admin panel
It would be nice to add sorting possibility to the `admin-blogs` table. 

I'm currently considering adding one more column to this table, so it would be nice if this solution would also support sorting by numeric values.

### PR DESCRIPTION
**Pull request by gsancewicz**
Hi. 
I needed to change BlogsPageRequestHandler in BlogsPage. When it was managed by spring container there were some issues with wicket deserializer. After deseralization there were more instances of this component and sorting was not working. 
I've added sorting indicators icons. Source of the icons is: https://svn.apache.org/repos/asf/wicket/branches/wicket-1.4.x/wicket-examples/src/main/webapp/images/ so i believe that license is ok. 
Finnaly i moved table generating method from DataView to DataTable. I've created BootstrapTable inspired by DefaultDataTable. 

This is my first pull request, and first time with wicket. So plese take a look two more times before merging :)

### CODE REVIEW

**Comment by airborn** [comment]
Regarding the icons. We are already using `fontawesome` in the backend so please consider using [sort-asc](http://fontawesome.io/icon/sort-asc/), [sort-desc](http://fontawesome.io/icon/sort-desc/) and [sort](http://fontawesome.io/icon/sort/)

**Comment by gsancewicz** [comment]
I changed icons to font-awesome. It was little harder than i thought it would be.

**Comment by airborn** [comment]
@gsancewicz I'm really sorry that it took so long for this PR to be reviewed and merged

**Comment by gsancewicz** [comment]
@airborn it's ok. Thanks for merging.

**Pull request merged**
